# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfe922385f598c87d71bdd77b2c851036f3ac15ec565e6ddfa08d08d6f1efd4fc8d0e795feb9ecd56f9679d1216a133c32d069ae4f78e8f2a4a9d7fac9c8a2b1

test:
  secret_key_base: d91419388c17bb532632eb057e903995c67a60deac019bfa6504e6b6c09f6e641f399dde4625c1029f7f2cd6cf371a69fbdb59541f6eb77a2dcd8433dfde54f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
